### ISSUE TITLE
Create the TextInput component 

### ISSUE THREAD

**Issue by FilipMessa** [kiwicom/universal-components#13]
via @lukewalczak 

TextInput is prepared, but need more features such as:

- [x] - TextInput with `ServiceLogo` suffix - PR #31 
- [ ] - TextInput with button link suffix -> depends on another component called `ButtonLink`
- [x] - TextInput types (number, password, email) - PR #34 
- [x] - TextInput helper - PR #43 
- [x] - TextInput test - PR #40 
- [x] - TextInput knobs - PR #36

**Comment by lukewalczak** [comment]
TextInput is prepared, but need more features such as:


- [ ] - TextInput suffix
- [ ] - TextInput types (number, password, email)
- [ ] - TextInput helper
- [ ] - TextInput test

**Comment by RobinCsl** [comment]
@FilipMessa 
Do we need 
> TextInput with button link suffix -> depends on another component called ButtonLink ?

**Comment by FilipMessa** [comment]
I checked it and from TextInput perspective, it is done, we miss the ButtonLink but it should be another issue https://orbit.kiwi/components/buttonlink/

**Comment by RobinCsl** [comment]
Actually, our Button component already has that in place: if you specify `href`, it will be rendered as an `a` tag in the DOM. (Will not do anything on mobile) Is that sufficient?

https://kiwicom-universal-components.netlify.com/?selectedKind=Button&selectedStory=Playground&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

**Comment by FilipMessa** [comment]
In that case, we can close this issue.
