### ISSUE TITLE
Remove `intl` package

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/universal-components#150]
That means:
- [x] removing post-install hooks; #154 
- [x] renaming `Price` component to `LocalizedPrice`, and assume that prop would be `localizedPrice: string`;  #151
- [x] DateFormatter can be removed; #153 
- [x] SearchParamsSummary should accept `localizedDate: string` in type Trip instead of Date. #152

**Comment by RobinCsl** [comment]
This corresponds to first step of #149
